In [2]:
import pandas as pd 
import numpy as np 


data = pd.read_csv("./data/player_stats_202122.csv", sep=';', encoding='ISO-8859-1')
data.head(5)

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,Off,Crs,TklW,PKwon,PKcon,OG,Recov,AerWon,AerLost,AerWon%
0,1,Max Aarons,ENG,DF,Norwich City,Premier League,22.0,2000,34,32,...,0.03,1.41,1.16,0.0,0.06,0.03,5.53,0.47,1.59,22.7
1,2,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,34.0,1987,34,34,...,0.00,0.06,1.39,0.0,0.03,0.00,6.77,2.02,1.36,59.8
2,3,Salis Abdul Samed,GHA,MF,Clermont Foot,Ligue 1,22.0,2000,31,29,...,0.00,0.36,1.24,0.0,0.00,0.00,8.76,0.88,0.88,50.0
3,4,Laurent Abergel,FRA,MF,Lorient,Ligue 1,29.0,1993,34,34,...,0.03,0.79,2.23,0.0,0.00,0.00,8.87,0.43,0.43,50.0
4,5,Charles Abi,FRA,FW,Saint-Étienne,Ligue 1,22.0,2000,1,1,...,0.00,2.00,0.00,0.0,0.00,0.00,4.00,2.00,0.00,100.0

In [3]:
data.columns[data.isnull().any()].tolist()

['Nation', 'Age']

In [19]:
football_player_stats = pd.DataFrame()

football_player_stats['Player'] = data['Player']
football_player_stats['Nation'] = data['Nation']
football_player_stats['Squad'] = data['Squad']
football_player_stats['League'] = data['Comp']
football_player_stats['Age'] = data['Age']
football_player_stats['MP'] = data['MP']
football_player_stats['Position'] = data['Pos']
football_player_stats['Goals/90'] = data['Goals']
football_player_stats['Goals/Shot'] = data['G/Sh']
football_player_stats['Shots'] = data['Shots']
football_player_stats['TouchesDefPen'] = data['TouDefPen']
football_player_stats['TouchesDef3rd'] = data['TouDef3rd']
football_player_stats['TouchesMid3rd'] = data['TouMid3rd']
football_player_stats['TouchesAtt3rd'] = data['TouAtt3rd']
football_player_stats['TouchesAttPen'] = data['TouAttPen']
football_player_stats['BlocksOnTargetShots'] = data['BlkShSv']
football_player_stats['BlocksShots'] = data['BlkSh']
football_player_stats['BlocksPasses'] = data['BlkPass']
football_player_stats['Blocks'] = (data['Blocks'] - (data['BlkShSv'] + data['BlkSh'] + data['BlkPass'])).round(0).astype(int)
football_player_stats['PKGoals'] = ((data['ShoPK'] * data['Min']) / 90).round(0).astype(int)
football_player_stats['PKAttempted'] = ((data['PKatt'] * data['Min']) / 90).round(0).astype(int)
football_player_stats['Goals'] = ((data['Goals'] * data['Min']) / 90).round(0).astype(int)
football_player_stats['Pass'] = ((data['PasTotAtt'] * data['Min']) / 90).round(0).astype(int)
football_player_stats['PassCompleted'] = ((data['PasTotCmp'] * data['Min']) / 90).round(0).astype(int)
football_player_stats['PassComp%'] = ((football_player_stats['PassCompleted'] / football_player_stats['Pass'])).round(2)
football_player_stats['Assist'] = ((data['Assists'] * data['Min']) / 90).round(0).astype(int)
football_player_stats['Cross'] = ((data['PasCrs'] * data['Min']) / 90).round(0).astype(int)
football_player_stats['CrossCompleted'] = ((data['CrsPA'] * data['Min']) / 90).round(0).astype(int)
football_player_stats['CrossComp%'] = ((football_player_stats['CrossCompleted'] / football_player_stats['Cross'])).round(2)
football_player_stats['Tackle_Won'] = ((data['TklWon'] * data['Min']) / 90).round(0).astype(int)
football_player_stats['SucDribble'] = ((data['DriSucc'] * data['Min']) / 90).round(0).astype(int)
football_player_stats['Dribble'] = ((data['DriAtt'] * data['Min']) / 90).round(0).astype(int)
football_player_stats['DribbleComp%'] = ((football_player_stats['SucDribble'] / football_player_stats['Dribble'])).round(2)
football_player_stats['YCards'] = ((data['CrdY'] * data['Min']) / 90).round(0).astype(int)
football_player_stats['RCards'] = ((data['CrdR'] * data['Min']) / 90).round(0).astype(int)
football_player_stats['FoulsCommitted'] = ((data['Fls'] * data['Min']) / 90).round(0).astype(int)
football_player_stats['FoulsDrawn'] = ((data['Fld'] * data['Min']) / 90).round(0).astype(int)
football_player_stats['OGoals'] = ((data['OG'] * data['Min']) / 90).round(0).astype(int)
football_player_stats['AerWon'] = ((data['AerWon'] * data['Min']) / 90).round(0).astype(int)
football_player_stats['AerLost'] = ((data['AerLost'] * data['Min']) / 90).round(0).astype(int)
football_player_stats['AerWon%'] = ((data['AerWon'] / (data['AerWon'] + data['AerLost'])) * 100).round(2)

football_player_stats.head()

,Player,Nation,Squad,League,Age,MP,Position,Goals/90,Goals/Shot,Shots,...,Dribble,DribbleComp%,YCards,RCards,FoulsCommitted,FoulsDrawn,OGoals,AerWon,AerLost,AerWon%
0,Max Aarons,ENG,Norwich City,Premier League,22.0,34,DF,0.00,0.00,0.41,...,78,0.42,8,0,31,59,1,15,51,22.82
1,Yunis Abdelhamid,MAR,Reims,Ligue 1,34.0,34,DF,0.06,0.11,0.54,...,22,0.73,5,1,43,24,0,67,45,59.76
2,Salis Abdul Samed,GHA,Clermont Foot,Ligue 1,22.0,31,MF,0.04,0.06,0.66,...,42,0.64,12,3,45,35,0,24,24,50.00
3,Laurent Abergel,FRA,Lorient,Ligue 1,29.0,34,MF,0.00,0.00,0.91,...,65,0.65,9,0,46,68,0,14,14,50.00
4,Charles Abi,FRA,Saint-Étienne,Ligue 1,22.0,1,FW,0.00,0.00,0.00,...,0,NaN,0,0,1,0,0,1,0,100.00

In [17]:
football_player_stats.keys()

Index(['Player', 'Nation', 'Squad', 'League', 'Age', 'MP', 'Position',
       'Goals/90', 'Goals/Shot', 'Shots', 'TouchesDefPen', 'TouchesDef3rd',
       'TouchesMid3rd', 'TouchesAtt3rd', 'TouchesAttPen',
       'BlocksOnTargetShots', 'BlocksShots', 'BlocksPasses', 'Blocks',
       'PKGoals', 'PKAttempted', 'Goals', 'Pass', 'PassCompleted', 'PassComp%',
       'Assist', 'Cross', 'CrossCompleted', 'CrossComp%', 'Tackle_Won',
       'SucDribble', 'Dribble', 'DribbleComp%', 'YCards', 'RCards',
       'FoulsCommitted', 'FoulsDrawn', 'OGoals', 'AerWon', 'AerLost',
       'AerWon%'],
      dtype='object')

We group the above attributes into the following categories:

## Attatcking Stats:
- Goals/Shot : 
- Shots : 
- PKGoals : 
- PKAttempted : 
- Goals : 
- TouchesAtt3rd : 
- TouchesAttPen : 

## Passing Stats:
- PassComp% : 

## Creativity:
- Assist :
- Cross : 
- CrossCompleted : 
- CrossComp% : 
- FoulsDrawn

## Tackles:
- Tackles_Won:
- TouchesDefPen
- TouchesDef3rd
- AerWon
- AerLost

<!-- ## Pressing: -->

## Blocks:
- Blocks
- BlocksShots
- BlocksShotsOnTarget
- BlocksPasses

## Dribbling:
- SucDribble
- Dribble
- DribbleComp%

## Indiscipline:
- Ycards
- RCards
- FoulsCommitted

In [20]:
Attack_Stats = football_player_stats[["Player", "Nation", "Squad", "League", "Age", "Position", "Goals", "Goals/Shot", "Shots", "PKGoals", "PKAttempted","TouchesAtt3rd", "TouchesAttPen"]]

Att_weights = [0.3,0.1,0.05,0.2,0.1,0.1,0.15]
Attack_Stats["Combined"] = Attack_Stats.iloc[:,6:].mul(Att_weights).sum(axis=1)
Attack_Stats = Attack_Stats.sort_values(by='Combined', ascending=False)
Attack_Stats.head()

/var/folders/qw/9j8hm051443c2lydt69r_n7w0000gn/T/ipykernel_40158/3154065245.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Attack_Stats["Combined"] = Attack_Stats.iloc[:,6:].mul(Att_weights).sum(axis=1)

,Player,Nation,Squad,League,Age,Position,Goals,Goals/Shot,Shots,PKGoals,PKAttempted,TouchesAtt3rd,TouchesAttPen,Combined
1512,Robert Lewandowski,POL,Bayern Munich,Bundesliga,33.0,FW,35,0.19,4.80,5,5,21.9,8.35,15.7015
2131,Jérémy Pied,FRA,Lille,Ligue 1,33.0,DFFW,0,0.00,0.00,0,0,140.0,10.00,15.5000
284,Karim Benzema,FRA,Real Madrid,La Liga,34.0,FW,27,0.17,4.10,7,11,33.7,8.02,15.3950
1720,Kylian Mbappé,FRA,Paris S-G,Ligue 1,23.0,FW,28,0.17,4.29,4,4,40.0,10.20,15.3615
792,Hugo Duro,ESP,Getafe,La Liga,22.0,DFMF,0,0.00,20.00,0,0,60.0,50.00,14.5000

In [22]:
# Pass_Stats = football_player_stats[["Player","Pass", "PassCompleted", "PassComp%"]]
Pass_Stats = football_player_stats[["Player", "Nation", "Squad", "League", "Age", "Position", "PassComp%"]]
Pass_weights = [1]
Pass_Stats["Combined"] = Pass_Stats.iloc[:,6:].mul(Pass_weights).sum(axis=1)
Pass_Stats = Pass_Stats.sort_values(by='Combined', ascending=False)
Pass_Stats.head()

/var/folders/qw/9j8hm051443c2lydt69r_n7w0000gn/T/ipykernel_40158/2887659541.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Pass_Stats["Combined"] = Pass_Stats.iloc[:,6:].mul(Pass_weights).sum(axis=1)

,Player,Nation,Squad,League,Age,Position,PassComp%,Combined
974,Alejandro Garnacho,ESP,Manchester Utd,Premier League,17.0,FW,1.0,1.0
2076,Federico Peluso,ITA,Sassuolo,Serie A,38.0,DF,1.0,1.0
643,Keinan Davis,ENG,Aston Villa,Premier League,24.0,FW,1.0,1.0
649,Tommaso De Nipoti,ITA,Atalanta,Serie A,18.0,MF,1.0,1.0
2889,Mattia Zanotti,ITA,Inter,Serie A,19.0,DF,1.0,1.0

In [24]:
Crea_Stats = football_player_stats[["Player", "Nation", "Squad", "League", "Age", "Position", "Assist", "CrossComp%","FoulsDrawn"]]

Crea_weights = [0.5,0.3,0.2]
Crea_Stats["Combined"] = Crea_Stats.iloc[:,6:].mul(Crea_weights).sum(axis=1)
Crea_Stats = Crea_Stats.sort_values(by='Combined', ascending=False)
Crea_Stats.head()

/var/folders/qw/9j8hm051443c2lydt69r_n7w0000gn/T/ipykernel_40158/116656782.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Crea_Stats["Combined"] = Crea_Stats.iloc[:,6:].mul(Crea_weights).sum(axis=1)

,Player,Nation,Squad,League,Age,Position,Assist,CrossComp%,FoulsDrawn,Combined
868,Nabil Fekir,FRA,Betis,La Liga,28.0,MF,8,0.05,117,27.415
1036,Nicolás González,ARG,Fiorentina,Serie A,24.0,FW,6,0.22,113,25.666
2881,Wilfried Zaha,CIV,Crystal Palace,Premier League,29.0,FW,1,0.31,124,25.393
1872,Iker Muniain,ESP,Athletic Club,La Liga,29.0,MF,10,0.15,99,24.845
258,Jude Bellingham,ENG,Dortmund,Bundesliga,18.0,MF,8,0.12,102,24.436

In [25]:
Tack_Stats = football_player_stats[["Player", "Nation", "Squad", "League", "Age", "Position", "Tackle_Won", "TouchesDefPen", "TouchesDef3rd","AerWon%"]]

Tack_weights = [0.4,0.2,0.15,0.25]
Tack_Stats["Combined"] = Tack_Stats.iloc[:,6:].mul(Tack_weights).sum(axis=1)
Tack_Stats = Tack_Stats.sort_values(by='Combined', ascending=False)
Tack_Stats.head()

/var/folders/qw/9j8hm051443c2lydt69r_n7w0000gn/T/ipykernel_40158/3639053203.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Tack_Stats["Combined"] = Tack_Stats.iloc[:,6:].mul(Tack_weights).sum(axis=1)

,Player,Nation,Squad,League,Age,Position,Tackle_Won,TouchesDefPen,TouchesDef3rd,AerWon%,Combined
1574,José Luis Palomino,ARG,Atalanta,Serie A,32.0,DF,66,7.17,30.9,72.22,50.5240
239,Rodrigo Becão,BRA,Udinese,Serie A,26.0,DF,72,6.75,25.2,65.83,50.3875
95,Benjamin André,FRA,Lille,Ligue 1,31.0,MF,78,4.02,19.0,59.29,49.6765
2622,Aurélien Tchouaméni,FRA,Monaco,Ligue 1,22.0,MF,67,2.52,16.6,71.05,47.5565
477,Casemiro,BRA,Real Madrid,La Liga,30.0,MF,64,6.28,26.1,67.06,47.5360

In [26]:
Block_Stats = football_player_stats[["Player", "Nation", "Squad", "League", "Age", "Position", "BlocksShots", "BlocksOnTargetShots","BlocksPasses"]]

Block_weights = [0.2,0.5,0.3]
Block_Stats["Combined"] = Block_Stats.iloc[:,6:].mul(Block_weights).sum(axis=1)
Block_Stats = Block_Stats.sort_values(by='Combined', ascending=False)
Block_Stats.head()

/var/folders/qw/9j8hm051443c2lydt69r_n7w0000gn/T/ipykernel_40158/2194548142.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Block_Stats["Combined"] = Block_Stats.iloc[:,6:].mul(Block_weights).sum(axis=1)

,Player,Nation,Squad,League,Age,Position,BlocksShots,BlocksOnTargetShots,BlocksPasses,Combined
991,Anwar El Ghazi,NED,Everton,Premier League,27.0,FW,0.0,0.0,20.0,6.0
829,Gonzalo Escalante,ARG,Lazio,Serie A,29.0,MF,10.0,0.0,10.0,5.0
854,Paolo Faragò,ITA,Cagliari,Serie A,29.0,MF,0.0,0.0,15.0,4.5
2037,Martin Palumbo,NOR,Juventus,Serie A,20.0,MF,0.0,0.0,10.0,3.0
2382,Juan Sánchez,ESP,Sevilla,La Liga,18.0,MF,0.0,0.0,10.0,3.0

In [27]:
Drib_Stats = football_player_stats[["Player", "Nation", "Squad", "League", "Age", "Position", "DribbleComp%", "TouchesMid3rd"]]

Drib_weights = [0.8,0.2]
Drib_Stats["Combined"] = Drib_Stats.iloc[:,6:].mul(Drib_weights).sum(axis=1)
Drib_Stats = Drib_Stats.sort_values(by='Combined', ascending=False)
Drib_Stats.head()

/var/folders/qw/9j8hm051443c2lydt69r_n7w0000gn/T/ipykernel_40158/795383187.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Drib_Stats["Combined"] = Drib_Stats.iloc[:,6:].mul(Drib_weights).sum(axis=1)

,Player,Nation,Squad,League,Age,Position,DribbleComp%,TouchesMid3rd,Combined
1501,Félix Lemaréchal,CIV,Monaco,Ligue 1,18.0,MF,0.5,150.0,30.4
2131,Jérémy Pied,FRA,Lille,Ligue 1,33.0,DFFW,NaN,120.0,24.0
731,Assane Dioussé,SEN,Saint-Étienne,Ligue 1,24.0,MF,NaN,100.0,20.0
762,Lohann Doucet,FRA,Nantes,Ligue 1,19.0,MF,NaN,100.0,20.0
2186,Niklas Pyyhtiä,FIN,Bologna,Serie A,18.0,MF,1.0,90.0,18.8

In [28]:
Indis_Stats = football_player_stats[["Player", "Nation", "Squad", "League", "Age", "Position", "YCards", "RCards", "FoulsCommitted"]]

Indis_weights = [0.2, 0.3, 0.5]
Indis_Stats["Combined"] = Indis_Stats.iloc[:,6:].mul(Indis_weights).sum(axis=1)
Indis_Stats = Indis_Stats.sort_values(by='Combined', ascending=False)
Indis_Stats.head()

/var/folders/qw/9j8hm051443c2lydt69r_n7w0000gn/T/ipykernel_40158/146335018.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Indis_Stats["Combined"] = Indis_Stats.iloc[:,6:].mul(Indis_weights).sum(axis=1)

,Player,Nation,Squad,League,Age,Position,YCards,RCards,FoulsCommitted,Combined
1582,Saa Luki?,SRB,Torino,Serie A,25.0,MF,10,0,91,47.5
1756,Brais Méndez,ESP,Celta Vigo,La Liga,25.0,MF,8,0,89,46.1
2648,Morten Thorsby,NOR,Sampdoria,Serie A,26.0,MF,10,0,87,45.5
2729,Enes Ünal,TUR,Getafe,La Liga,25.0,FW,8,0,86,44.6
956,Conor Gallagher,ENG,Crystal Palace,Premier League,22.0,MF,10,0,84,44.0

In [29]:
Composite_Table = pd.DataFrame()

Composite_Table["Player"] = Attack_Stats["Player"]
Composite_Table["Attack"] = Attack_Stats["Combined"]
Composite_Table["Pass"] = Pass_Stats["Combined"]
Composite_Table["Creativity"] = Crea_Stats["Combined"]
Composite_Table["Tackles"] = Tack_Stats["Combined"]
Composite_Table["Blocks"] = Block_Stats["Combined"]
Composite_Table["Dribbling"] = Drib_Stats["Combined"]
Composite_Table["Indiscipline"] = Indis_Stats["Combined"]
Composite_Table["Nation"] = football_player_stats["Nation"]
Composite_Table["Squad"] = football_player_stats["Squad"]
Composite_Table["League"] = football_player_stats["League"]
Composite_Table["Age"] = football_player_stats["Age"]
Composite_Table["Position"] = football_player_stats["Position"]
Composite_Table.head()

,Player,Attack,Pass,Creativity,Tackles,Blocks,Dribbling,Indiscipline,Nation,Squad,League,Age,Position
1512,Robert Lewandowski,15.7015,0.77,10.330,15.788,0.207,3.396,12.9,POL,Bayern Munich,Bundesliga,33.0,FW
2131,Jérémy Pied,15.5000,0.70,0.000,33.000,0.000,24.000,0.0,FRA,Lille,Ligue 1,33.0,DFFW
284,Karim Benzema,15.3950,0.85,8.445,10.007,0.105,4.508,7.0,FRA,Real Madrid,La Liga,34.0,FW
1720,Kylian Mbappé,15.3615,0.80,20.648,13.614,0.045,4.800,15.5,FRA,Paris S-G,Ligue 1,23.0,FW
792,Hugo Duro,14.5000,0.80,0.200,12.500,0.000,0.000,0.5,ESP,Getafe,La Liga,22.0,DFMF